[www]
user=www-data
group=www-data
listen=9000

pm = dynamic
pm.max_children = 80
pm.start_servers = 8
pm.min_spare_servers = 8
pm.max_spare_servers = 20
pm.max_requests = 1000
pm.process_idle_timeout = 10s

catch_workers_output = yes
clear_env = no

slowlog = /var/log/php-fpm/www-slow.log
request_slowlog_timeout = 10s

rlimit_files = 65536
listen.backlog = 65535